image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
      gp ports await 8080
      gp preview $(gp url 8080)
ports:
  - port: 8080
    onOpen: open-browser
  - port: 8090
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mtxr.sqltools-driver-mssql